/*
===============================================================================
Project      : Mobile Sales Analytics
Author       : Yashsvi Sharma
Database     : MySQL

Description:
This script contains beginner-friendly business SQL queries performed on the
Mobile Sales dataset. These queries focus on understanding overall business
performance using aggregate functions and basic filtering.
===============================================================================
*/

/*==============================================================================
Question 1
Find the total revenue generated by the business.
==============================================================================*/

SELECT
SUM(Units_Sold * Price_Per_Unit) AS Total_Revenue
FROM mobile_sales;

/*==============================================================================
Question 2
Find the total number of mobile phones sold.
==============================================================================*/

SELECT
SUM(Units_Sold) AS Total_Units_Sold
FROM mobile_sales;

/*==============================================================================
Question 3
Find the average customer rating.
==============================================================================*/

SELECT
ROUND(AVG(Customer_Ratings),2) AS Average_Customer_Rating
FROM mobile_sales;

/*==============================================================================
Question 4
Find the total number of transactions.
==============================================================================*/

-- Preferred Solution

SELECT
COUNT(*) AS Total_Transactions
FROM mobile_sales;

-- Alternate Solution

SELECT
COUNT(Transaction_ID) AS Total_Transactions
FROM mobile_sales;

/*==============================================================================
Question 5
Find the average selling price of a mobile phone.
==============================================================================*/

SELECT
ROUND(AVG(Price_Per_Unit),2) AS Average_Selling_Price
FROM mobile_sales;

/*==============================================================================
Question 6
Find the total revenue generated through each payment method.
==============================================================================*/

SELECT
Payment_Method,
SUM(Units_Sold * Price_Per_Unit) AS Revenue
FROM mobile_sales
GROUP BY Payment_Method
ORDER BY Revenue DESC;

/*==============================================================================
Question 7
Find the highest-priced mobile sold.
==============================================================================*/

SELECT
MAX(Price_Per_Unit) AS Highest_Price
FROM mobile_sales;

/*==============================================================================
Question 8
Find the lowest-priced mobile sold.
==============================================================================*/

SELECT
MIN(Price_Per_Unit) AS Lowest_Price
FROM mobile_sales;

/*==============================================================================
Question 9
Find the total revenue generated by each brand.
==============================================================================*/

SELECT
Brand,
SUM(Units_Sold * Price_Per_Unit) AS Revenue
FROM mobile_sales
GROUP BY Brand
ORDER BY Revenue DESC;

/*==============================================================================
Question 10
Find the top 5 cities based on total revenue.
==============================================================================*/

SELECT
City,
SUM(Units_Sold * Price_Per_Unit) AS Revenue
FROM mobile_sales
GROUP BY City
ORDER BY Revenue DESC
LIMIT 5;

